# Generated by Django 6.0 on 2025-12-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('Admin_Right', models.BooleanField(default=False)),
                ('oauth_User_Id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('bio', models.TextField(max_length=300)),
                ('batch', models.CharField(max_length=10)),
                ('dept_info', models.CharField(max_length=50)),
                ('no_of_downloads', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.location')),
                ('event_cc_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_cc_id', to='myapp.user')),
                ('event_head_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_head_id', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermarked', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('camera_model', models.CharField(max_length=30)),
                ('aperture', models.CharField(max_length=30)),
                ('shutter_speed', models.CharField(max_length=30)),
                ('gps_Location', models.CharField(max_length=100)),
                ('total_Views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.events')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.location')),
                ('uploader_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_description', models.TextField(max_length=50)),
                ('confidence_Score', models.FloatField()),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.photo')),
                ('tagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_by', to='myapp.user')),
                ('tagged_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_whom', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reference_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.photo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
                ('photoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.photo')),
                ('activity_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.photo')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.photo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.photo')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark_desc', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.photo')),
            ],
        ),
    ]
