# Generated by Django 6.0 on 2025-12-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_watermark_owner_alter_photo_uploader_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_cc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_cc_id', to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_head_id', to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='activity_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='reference_photo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_by', to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagged_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_whom', to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='watermark',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
