# Generated by Django 6.0 on 2025-12-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_comment_commented_by_alter_events_event_cc_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='ActivityOnPhoto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='newEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='new_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='new_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='new_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='new_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='camera_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gps_Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
