# Generated by Django 6.0 on 2025-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_events_event_remove_photo_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(default=1, max_length=56),
            preserve_default=False,
        ),
    ]
