# Generated by Django 6.0 on 2025-12-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_otpverification_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
    ]
