# Generated by Django 6.0 on 2025-12-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_only',
            field=models.BooleanField(default=False),
        ),
    ]
