# Generated by Django 6.0 on 2025-12-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_event_member_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_cc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_cc_id', to='myapp.profile'),
        ),
    ]
