# Generated by Django 6.0 on 2025-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_event_event_cc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='oauth_User_Id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
