# Generated by Django 6.0 on 2025-12-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_profile_oauth_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_cc_id',
            new_name='event_cc',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_head_id',
            new_name='event_head',
        ),
    ]
