# Generated by Django 6.0 on 2026-01-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='event_id',
            new_name='event',
        ),
    ]
