# Generated by Django 6.0 on 2026-01-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_event_id_photo_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watermark',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/originals'),
        ),
    ]
