# Generated by Django 6.0 on 2026-01-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_photo_id_watermark_photo_photo_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liked_by', 'photo')},
        ),
    ]
