# Generated by Django 6.0 on 2026-01-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_photo_id_comment_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reference_photo',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='reference_photo',
            old_name='user_id',
            new_name='user',
        ),
    ]
