# Generated by Django 6.0 on 2026-01-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_photo_id_favourite_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='photo_id',
            new_name='photo',
        ),
    ]
