# Generated by Django 6.0 on 2026-01-27 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_photo_id_tag_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upload_access_users',
            field=models.ManyToManyField(blank=True, related_name='upload_access_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
