# Generated by Django 6.0 on 2026-01-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_event_upload_access_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ai_tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
