# Generated by Django 6.0 on 2026-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_photo_ai_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/watermarked/'),
        ),
    ]
