from django.urls import path,include
from . import views

urlpatterns = [
    path('api/send-otp/', views.send_otp, name='send_otp'),
    path('api/verify-otp/', views.verify_otp, name='verify_otp'),
    path('api/verify-login/',views.verify_login,name='verify-login'),
    path('api/logout_session/',views.logout_session,name='logout_session'),
    path('api/dashboard/',views.dashboard,name='dashboard'),
    path('api/check_auth/',views.check_auth,name='check_auth'),
    path('api/view_profile/',views.view_profile,name='view_profile'),
    path('api/view_events/',views.view_events,name='view_events'),
    path('api/view_my_events/',views.view_my_events,name='view_my_events'),
    path('api/check_guest/',views.check_guest,name='check_guest'),
    path('api/addnew_event/',views.addnew_event,name='addnew_event'),  
    path('api/event_photos/<str:event_slug>/',views.event_photos,name='event_photos'), 
    path('api/check_photographer/<str:event_slug>/',views.check_photographer,name='check_photographer'),
    path('api/upload_photos/',views.upload_photos,name='upload_photos'),
    path('api/photo_properties/',views.photo_properties,name='photo_properties'),
    path('api/toggle_like/',views.toggle_like,name='toggle_like'),
    path('api/toggle_favourite/',views.toggle_favourite,name='toggle_favourite'),
    path('api/favourite_photos/',views.favourite_photos,name='favourite_photos'),
    path('api/update_profile_picture/',views.update_profile_picture,name='update_profile_picture'), 
    path('api/update_bio/',views.update_bio,name='update_bio'),
    path('api/load_tagged_users/',views.load_tagged_users,name='load_tagged_users'),
    path('api/tagUser/',views.tagUser,name='tagUser'),
    path('api/tag_user/',views.tagUser,name='tag_user_alias'),
    path('api/search_users/',views.search_users,name='search_users'),
    path('api/search/',views.search_photos,name='search_photos'),
    path('api/tagged_images/',views.tagged_images,name='tagged_images'),
    path('api/load_comments/',views.load_comments,name='load_comments'),
    path('api/add_comment/',views.add_comment,name='add_comment'),
    path('api/download_photo/<int:photo_id>/',views.download_photo,name='download_photo'),
    path('api/delete_event/<int:event_id>/',views.delete_event,name='delete_event'),
    path('api/get_event_photographers/<int:event_id>/',views.get_event_photographers,name='get_event_photographers'),
    path('api/toggle_photographer_access/<int:event_id>/',views.toggle_photographer_access,name='toggle_photographer_access'),
    path("api/set-csrf/", views.set_csrf),
    path('api/delete_photos/<str:event_slug>/',views.delete_photos,name='delete_photos'),

    
]